import { Animation } from './animation.js'
import { CANVAS_SIZE, TILE_SIZE } from './globals.js'

/**
 * @typedef {Object} CharacterMeta
 * @property {import('./animation').AnimationsMap} CharacterMeta.animationsMap
 * @property {import('./vector').Vector} CharacterMeta.position
 * @property {CanvasRenderingContext2D} ctx
 */

class Character {
  /**
   * @param {CharacterMeta} characterMeta
   */
  constructor({ animationsMap, position, ctx }) {
    /**
     * Animation for the current action.
     *
     * Set by `setCurrentAnimation`.
     *
     * @private
     *
     * @type {Animation}
     */
    this.currentAnimation = undefined

    /**
     * Current animation frame index.
     *
     * Set by `setCurrentAnimation` and `getNextAnimationFrame`.
     *
     * @private
     *
     * @type {number}
     */
    this.currentAnimationFrameIndex = undefined

    /**
     * If the current animation frame has lasted enough time according to `Animation.frameDuration`.
     *
     * If true, `currentAnimationFrameIndex` would change at next render.
     *
     * Set by `setCurrentAnimation` and `getNextAnimationFrame`.
     *
     * @private
     *
     * @type {boolean}
     */
    this.isCurrentAnimationFrameDone = undefined

    /**
     * Animation frame index iterator for the current action.
     *
     * Generated by `Animation.fromEntries`. Set by `setCurrentAnimation`.
     *
     * @private
     *
     * @generator
     */
    this.animationFrameIndexIterator = undefined

    /**
     * If the character will stop to `idle` at next render.
     *
     * Set back to false in `stop`.
     *
     * @public
     */
    this.willStop = false

    /**
     * All the actions to take at each render.
     *
     * An array of tuple `[predicate, action]`.
     *
     * @private
     *
     * @type {Array<[predicate: (() => boolean), action: (() => void)]>}
     */
    this._actions = []

    // Add `move` to `_actions` by default.
    this.addAction([this.willMove, this.move])

    /**
     * The actual action name. Default is `idle`.
     *
     * @private
     */
    this._action = 'idle'

    /**
     * Action name in it will be prioritized if other action has already been set.
     *
     * Default value is an empty array.
     *
     * @protected
     *
     * @type {string[]}
     */
    this.prioritizedActions = []

    /**
     * Moving directions.
     *
     * @public
     */
    this.directions = { up: false, right: false, down: false, left: false }

    /**
     * Default moving speed. Pixels per render.
     *
     * @protected
     */
    this.speed = 2

    /**
     * Which side is the character facing. Sprite would be flipped if facing left.
     *
     * Chanaged by `move`.
     *
     * @private
     */
    this.face = 'right'

    /**
     * The actual rendered times. Used for controlling actions interval.
     *
     * Increased by `render`.
     *
     * @protected
     */
    this.renderedTimes = 0

    /**
     * The provided animations map.
     *
     * @private
     */
    this.animationsMap = animationsMap

    this.setCurrentAnimation()

    /**
     * Current position in the layer. Default value is provided by argument.
     *
     * @protected
     */
    this.position = position

    /**
     * Canvas context for rendering.
     *
     * @private
     */
    this.ctx = ctx
  }

  /**
   * Add a tuple of action predicate and action function to the start of `_actions`.
   *
   * @protected
   *
   * @param {[predicate: (() => boolean), action: (() => void)]} fns
   */
  addAction(fns) {
    this._actions.unshift(fns.map(fn => fn.bind(this)))
  }

  /**
   * Action getter for `_action`.
   *
   * @protected
   */
  get action() {
    return this._action
  }

  /**
   * Set animation according to current action.
   *
   * Should only be called by `setAction`
   *
   * @private
   */
  setCurrentAnimation() {
    this.currentAnimation = this.animationsMap[this.action]
    this.currentAnimationFrameIndex = 0
    this.isCurrentAnimationFrameDone = false
    this.animationFrameIndexIterator = Animation.makeFrameIndexIterator(
      this.currentAnimation.frames.length,
      this.currentAnimation.frameDuration
    )
  }

  /**
   * Get current animation frame according to `currentFrameIndex`.
   *
   * @private
   */
  getCurrentAnimationFrame() {
    return this.currentAnimation.frames[this.currentAnimationFrameIndex]
  }

  /**
   * Get next animation frame according to the next frame index generated by `animationFrameIndexIterator`.
   *
   * @private
   */
  getNextAnimationFrame() {
    const {
      frameIndex,
      isFrameDone
    } = this.animationFrameIndexIterator.next().value

    if (isFrameDone) {
      this.currentAnimationFrameIndex = frameIndex
    }
    this.isCurrentAnimationFrameDone = isFrameDone

    return this.getCurrentAnimationFrame()
  }

  /**
   * Stop action.
   *
   * Change `willStop` back to `false` if successfully set action to `idle`.
   *
   * @protected
   */
  stop() {
    if (this.action !== 'idle') {
      const isSet = this.setAction('idle')
      if (!isSet) {
        return
      }
    }
    this.willStop = false
  }

  /**
   * Call the actions if their predicates are fulfilled.
   *
   * @private
   */
  act() {
    this._actions.forEach(([predicate, action]) => {
      if (predicate()) {
        action()
      }
    })
  }

  /**
   * Action setter.
   *
   * Set the given action if the character has no other actions.
   *
   * `idle` will be interrupted and action in `prioritizedActions` will be prioritized.
   *
   * Return whether the action has been successfully set.
   *
   * @private
   *
   * @param {string} actionName
   * @returns {boolean} isSet
   */
  setAction(actionName) {
    if (
      !this.isCurrentAnimationFrameDone &&
      this.action !== 'idle' &&
      !this.prioritizedActions.includes(actionName)
    ) {
      return false
    }

    this._action = actionName
    this.setCurrentAnimation()
    return true
  }

  /**
   * If the character will move at next render.
   *
   * Decide by checking whether exists true value in `directions`.
   *
   * @private
   */
  willMove() {
    for (const directionName in this.directions) {
      if (this.directions[directionName]) {
        return true
      }
    }

    return false
  }

  /**
   * Move action.
   *
   * Change `face` if turns direction from left to right or from right to left.
   *
   * Stop when will collide with wall.
   *
   * @private
   */
  move() {
    if (this.action !== 'move') {
      const isSet = this.setAction('move')
      if (!isSet) {
        return
      }
    }

    const originalPosition = { ...this.position }

    if (this.directions.up) {
      this.position.y -= this.speed
    }
    if (this.directions.right) {
      this.position.x += this.speed
      if (!this.directions.left) {
        this.face = 'right'
      }
    }
    if (this.directions.down) {
      this.position.y += this.speed
    }
    if (this.directions.left) {
      this.position.x -= this.speed
      if (!this.directions.right) {
        this.face = 'left'
      }
    }

    const currentAnimationFrame = this.getCurrentAnimationFrame()

    if (
      this.position.x <= TILE_SIZE ||
      this.position.x + currentAnimationFrame.width >=
        CANVAS_SIZE - TILE_SIZE ||
      this.position.y <= TILE_SIZE ||
      this.position.y + currentAnimationFrame.height >=
        CANVAS_SIZE - TILE_SIZE - 4
    ) {
      this.position = originalPosition
    }
  }

  /**
   * Render the character to the current layer.
   *
   * Increase `renderedTimes` by 1 at the end.
   *
   * @public
   */
  render() {
    const currentAnimationFrame = this.getCurrentAnimationFrame()

    this.ctx.clearRect(
      this.position.x,
      this.position.y,
      currentAnimationFrame.width,
      currentAnimationFrame.height
    )

    if (this.willStop) {
      this.stop()
    } else {
      this.act()
    }

    const nextAnimationFrame = this.getNextAnimationFrame()

    const drawImage = (dx, dy) => {
      this.ctx.drawImage(
        nextAnimationFrame.spriteSheet,
        nextAnimationFrame.position.x,
        nextAnimationFrame.position.y,
        nextAnimationFrame.width,
        nextAnimationFrame.height,
        dx,
        dy,
        nextAnimationFrame.width,
        nextAnimationFrame.height
      )
    }

    if (this.face === 'left') {
      /**
       * {@link https://stackoverflow.com/a/37388113/13346012
       * |How to flip images horizontally with HTML5}
       */
      this.ctx.save()
      this.ctx.translate(
        this.position.x + nextAnimationFrame.width / 2,
        this.position.y + nextAnimationFrame.height / 2
      )
      this.ctx.scale(-1, 1)
      drawImage(-nextAnimationFrame.width / 2, -nextAnimationFrame.height / 2)
      this.ctx.restore()
    } else {
      drawImage(this.position.x, this.position.y)
    }

    this.renderedTimes++
  }
}

/**
 * Charactor that can attack.
 */
export class AttackerCharacter extends Character {
  /**
   * @param {CharacterMeta} characterMeta
   */
  constructor(characterMeta) {
    super(characterMeta)

    this.addAction([() => this.willAttack, this.attack])

    this.prioritizedActions.push('attack')

    /**
     * If the character will attack at next render.
     *
     * @public
     */
    this.willAttack = false

    /**
     * If the character has already attacked once.
     *
     * `attack` sets it to `true` and `stop` sets it back to `false`.
     *
     * @private
     */
    this.hasAttacked = false

    /**
     * Default attack interval. The unit is rendered time.
     *
     * @private
     */
    this.attackInterval = 36

    /**
     * Last time the character attacked. Use `renderedTimes`.
     *
     * @private
     *
     * @type {number}
     */
    this.lastAttack = undefined
  }

  /**
   * Attack action.
   *
   * Return in advance if the character has already attacked before `stop`
   * or the frames interval between two attacks is less than `attackInterval`.
   *
   * Change `hasAttacked` to `true`.
   *
   * @protected
   */
  attack() {
    if (this.hasAttacked) {
      this.willStop = true
      return
    }

    if (this.renderedTimes - this.lastAttack < this.attackInterval) {
      return
    }

    this.setAction('attack')
    this.hasAttacked = true
    this.lastAttack = this.renderedTimes
  }

  /**
   * Override `Character.stop`.
   *
   * Change `hasAttacked` back to false.
   *
   * @override
   * @protected
   */
  stop() {
    super.stop()
    this.hasAttacked = false
  }
}
